#! /bin/sh
###########
# Startup #
###########
### Nvidia Configuration
killall plank &
sleep 2 && plank &
### System Tray
xfce4-panel &
killall krunner &
nvidia-settings -l &
### Compositor
picom --refresh-rate 144 --vsync --resize-damage 15 --backend glx --config ~/.config/picom.conf &
### Polybar
#polybar secondary &
### Unwanted Stuff
killall ibus-daemon &
### Keyring daemon
#gnome-keyring-daemon --unlock &
### Shortkeys
sxhkd &
### Start KDEconnect
kdeconnect-indicator &
### Mouse Pointer
xsetroot -cursor_name left_ptr &
### Raven
budgie-panel &
budgie-polkit-dialog &
### Wallpaper Setup
xfsettingsd &
feh --bg-fill /home/ghome/Pictures/Wallpapers/1.jpg &
udisksctl mount --object-path block_devices/sda4 &
udisksctl mount --object-path block_devices/sdb2 &
udisksctl mount --object-path block_devices/sdc2 &
udisksctl mount --object-path block_devices/sdd2 &
udisksctl mount --object-path block_devices/sdb1 &
udisksctl mount --object-path block_devices/sdb5 &
latte-dock &
Spotify &
bash /home/ghome/Apps/bspwm_scr/floatingpro.sh &
#################
#    BSPWM Config   #
#################
### Creating Workspaces
bspc monitor DP-4 -d Music Browsing Terminal Gaming Content Sound Other Chats Pro Calls Virtual VClient Photos Videos Coding Files School &
bspc monitor HDMI -d Secondary &
### Tiling Setup
bspc config split_ratio 0.57 &
## Border
bspc config border_width 0 &
bspc config window_gap 8 &
bspc config split_ratio 0.52 &
bspc config top_padding 24 &
bspc config bottom_padding 42 & 
bspc config focused_border_color '#001448' &
bspc config normal_border_color '#838388' &
bspc config active_border_color '#838388' &
bspc config presel_feedback_color '#838388' &
### Other Config
bspc config borderless_monocle true & 
bspc config gapless_monocle true &
bspc config paddingless_monocle true &
bspc config single_monocle false &
## Focus Follow pointer
bspc config focus_follows_pointer true &
## Make pointer refresh with monitor
bspc config pointer_motion_interval 1 &


# Window rules
bspc rule -a Spotify desktop='Music' state=floating follow=on &
bspc rule -a Firefox desktop='Browsing' follow=on &
bspc rule -a Carla2 desktop='Sound' follow=on &
bspc rule -a Pavucontrol desktop='Sound' follow=on &
bspc rule -a discord desktop='Chats' follow=false &
bspc rule -a org.gnome.Epiphany.WebApp-messenger-68074b808a6b4cb6bfdef8565357226035058dd9 desktop='Chats' follow=false &
bspc rule -a Brave-browser desktop='Browsing' follow=on &
bspc rule -a Code desktop='Content' follow=on & 
bspc rule -a resolve desktop='Videos' follow=true & 
bspc rule -a Inkscape desktop='Content' follow=true & 
bspc rule -a Gimp-2.10 desktop='Content' follow=true & 
bspc rule -a steam_app_1182480 desktop='Other' follow=false & 
bspc rule -a Geany desktop='Terminal' follow=true &
bspc rule -a Budgie-polkit-dialog state=floating follow=on &b
bspc rule -a Steam desktop='Gaming' follow=off &
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Gnome-control-center state=floating
bspc rule -a cava state=floating desktop='Music' rectangle=1500x150+1500+800
bspc rule -a Shotcut desktop='Other' follow=true
bspc rule -a Simplenote desktop='Pro' follow=true
bspc rule -a Todoist desktop='Pro' follow=true
bspc rule -a jetbrains-pycharm-ce desktop=Content
bspc rule -a "Microsoft Teams - Preview" desktop=Calls
bspc rule -a "Eog" state=floating
bspc rule -a "ICE-SSB-notion" state=floating desktop=Pro
bspc rule -a "budgie-panel" hidden=on state=floating
bspc rule -a "Budgie-panel" sticky=on state=floating hidden=on
