#! /bin/sh
###########
# Startup #
###########
### Wallpaper Setup
feh --bg-fill /home/ghome/Git-Downloads/Dotfiles/.wallpapers/Neon.png
### Compositor
picom --refresh-rate 144 --vsync --resize-damage 15 --backend glx --config ~/.config/picom.conf &
### Polybar
polybar secondary &
### Unwanted Stuff
killall ibus-daemon &
### Keyring daemon
gnome-keyring-daemon --unlock &
### System Tray
xfce4-panel &
### Shortkeys
sxhkd &
### Nvidia Configuration
nvidia-settings -l &
### Starting Dunst
dunst -conf /home/ghome/.config/dustrc &
### Start KDEconnect
kdeconnect-indicator &
### Mouse Pointer
xsetroot -cursor_name left_ptr &


#################
#    BSPWM Config   #
#################
### Creating Workspaces
bspc monitor -d Terminal Browsing Music Gaming Content Sound Other Another &
### Tiling Setup
bspc config border_width 0 &
bspc config window_gap 20 &
bspc config split_ratio 0.52 &
bspc config top_padding 20 &
bspc config bottom_padding 22 & 
### Other Config
bspc config borderless_monocle true & 
bspc config gapless_monocle true &
bspc config paddingless_monocle true &
bspc config single_monocle false &
## Focus Follow pointer
bspc config focus_follows_pointer true &
## Make pointer refresh with monitor
bspc config pointer_motion_interval 1 &


# Window rules
bspc rule -a Spotify desktop='Music' state=floating follow=on &
bspc rule -a Firefox desktop='Browsing'
bspc rule -a Carla2 desktop='Sound' follow=on 
bspc rule -a Pavucontrol desktop='Sound' follow=on 
bspc rule -a discord desktop='Gaming' follow=false
bspc rule -a Brave-browser desktop='Browsing' follow=on 
bspc rule -a Code desktop='Content' follow=on
bspc rule -a resolve desktop='Content' follow=false
