#! /bin/sh
###########
# Startup #
###########
### Nvidia Configuration
killall krunner &
nvidia-settings -l &
### Compositor
picom --refresh-rate 144 --vsync --resize-damage 15 --backend glx --config ~/.config/picom.conf &
### Polybar
#polybar secondary &
### Unwanted Stuff
killall ibus-daemon &
### Keyring daemon
gnome-keyring-daemon --unlock &
### System Tray
xfce4-panel &
### Shortkeys
sxhkd &
### Starting Dunst
dunst -conf /home/ghome/.config/dustrc &
### Start KDEconnect
kdeconnect-indicator &
### Mouse Pointer
xsetroot -cursor_name left_ptr &
### Raven
budgie-panel &
budgie-polkit-dialog &
### Wallpaper Setup
feh --bg-fill /home/ghome/Pictures/Wallpapers/pro.jpeg &

#################
#    BSPWM Config   #
#################
### Creating Workspaces
bspc monitor DP-4 -d Terminal Browsing Music Gaming Content Sound Other Chats Pro Calls Virtual &
bspc monitor HDMI -d Secondary &
### Tiling Setup
bspc config split_ratio 0.57 &
## Border
bspc config border_width 0 &
bspc config window_gap 20 &
bspc config split_ratio 0.52 &
bspc config top_padding 14 &
bspc config bottom_padding 24 & 
bspc config focused_border_color '#001448' &
bspc config normal_border_color '#838388' &
bspc config active_border_color '#838388' &
bspc config presel_feedback_color '#838388' &
### Other Config
bspc config borderless_monocle true & 
bspc config gapless_monocle true &
bspc config paddingless_monocle true &
bspc config single_monocle false &
## Focus Follow pointer
bspc config focus_follows_pointer true &
## Make pointer refresh with monitor
bspc config pointer_motion_interval 1 &


# Window rules
bspc rule -a Spotify desktop='Music' state=floating follow=on &
bspc rule -a Firefox desktop='Browsing' &
bspc rule -a Carla2 desktop='Sound' follow=on &
bspc rule -a Pavucontrol desktop='Sound' follow=on &
bspc rule -a discord desktop='Chats' follow=false &
bspc rule -a org.gnome.Epiphany.WebApp-messenger-68074b808a6b4cb6bfdef8565357226035058dd9 desktop='Chats' follow=false &
bspc rule -a Brave-browser desktop='Browsing' follow=on &
bspc rule -a Code desktop='Content' follow=on & 
bspc rule -a resolve desktop='Content' follow=true & 
bspc rule -a Inkscape desktop='Content' follow=true & 
bspc rule -a Gimp-2.10 desktop='Content' follow=true & 

bspc rule -a steam_app_1182480 desktop='Another' follow=false & 
bspc rule -a Geany desktop='Terminal' follow=true &
bspc rule -a Budgie-polkit-dialog state=floating follow=on &
bspc rule -a steam desktop='Gaming' follow=off &
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a Gnome-control-center state=floating
